# ✏️ 학습내용
## 네트워크 프로그램 - 자원정리 
프로그램이 비정상적으로 종료되더라도, 반드시 사용하던 외부의 자원은 종료해주어야한다. 
하지만 try catch finally를 제대로 사용하지 않으면 외부자원이 정리되지 않은 상태로 예외가 던져지고 심각한 문제를 야기할 수 있다. 
이런 상황에 대비해 자원정리를 제대로 하는 법을 알아보았다.

```java
public void run() {
		DataInputStream input = null;
		DataOutputStream output = null;
		try {
			 input = new DataInputStream(socket.getInputStream());
			 output = new DataOutputStream(socket.getOutputStream());

			while(true) {
				// ... IO Exception 발생
			}
		} catch (IOException e) {
			log(e);
		} finally {
			closeAll(socket,input,output);
		}
```
이렇게 하면 while문안에서 예외가 발생하더라도 외부자원을 정리할 수 있게된다. 
하지만 만약 finally 블록에서 자원을 정리하지 않고 아래 예시처럼 try 내부에서 정리를 한다면 while문 안에서 에러가 발생시 예외만 던져지고 자원은 정리되지 않을것이다. 
```java
	public void run() {
		try {
			DataInputStream input = new DataInputStream(socket.getInputStream());
			DataOutputStream output = new DataOutputStream(socket.getOutputStream());

			while(true) {
				// ... IO Exception 발생
			}

			// 자원 정리
			log("연결 종료: " + socket);
			input.close();
			output.close();
			socket.close();
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
	}
```

# #️⃣ 생각해볼 문제
# 💫 학습자료